### ISSUE TITLE
Doesn't work with memory layers 

### ISSUE THREAD

**Issue by antoniusz** [nextgis/qgis_geometry_paster#11] opened 2023-11-24 08:46 UTC

**Comment by ivanbarsukov** [comment] 2023-12-08 11:48
Can you please provide more information? Did the layer have any attributes, or just geometry?

**Comment by jkr-wrk** [comment] 2023-12-13 11:49
@antoniusz 

Could you try drawing a temporary part with the QGis Add Part function and then pasting your geometry over that part? I would like to know if it is similar to my bug.

**Comment by ivanbarsukov** [comment] 2024-01-02 02:26
I am closing the issue because it is not reproducible. If it happens again, feel free to reopen.

**Closed by ivanbarsukov** 2024-01-02 02:26 UTC
Labels: enhancement
